#!/bin/bash

WORKDIR="/chronos/new/stream-grab-and-transcode" # » provide absolute path to the root of this directory
LOGDIR=$WORKDIR"/log"

STREAM="https://stream.me/collapz" # » target to grab e.g. https://stream.me/collapz
#STREAM="https://www.youtube.com/watch?v=___________" # » Use unshortened (!= youtu.be) links for YouTube targets!

PLAYER="mpv" # » vlc would work just as fine
PLAYER_OPTIONS="--mute" # » pass options to your chosen player

# ===
# Coloring - Terminal Colors
# ===
BLUE='\033[0;34m'
NC='\033[0m'

