#!/bin/bash
source config

mkdir -p out/$srcstring
mkdir -p raw-src/$srcstring

cd $WORKDIR/src/$srcstring;
shopt -s nullglob

notify_output(){
    cat $LOGDIR/ffmpeg.log |
        awk '!seen[$0]++' |
        sed 's/\x1b\[[0-9;]*m//g' |
        sed -n '/Metadata/,$p' |
        sed -n '/frame.*/q;p' |
        head -c 1900 |
        sed -e "1s/^/\`\`\`arm\\n/" -e "\$s/\$/\\n\`\`\`/" |
        apprise "$APPRISE_HOOK_TARGET";
}

notify()
{
    if [ ! -z "$APPRISE_HOOK_TARGET" ]; then
        cat $LOGDIR/ffmpeg.log |
            awk '!seen[$0]++' |
            sed 's/\x1b\[[0-9;]*m//g' |
            sed -n '/Metadata.*/q;p' |
            head -c 1900 |
            sed -e "1s/^/\`\`\`arm\\n/" -e "\$s/\$/\\n\`\`\`/" |
            sed -e "1s/^/\\nEncoder\ flags\:\\n\`$ENCODER_FLAGS\`\\n\\n/" |
            apprise -t "$NOTIFY_JOB_RUNNING" "$APPRISE_HOOK_TARGET";
            notify_output
       else
            true
    fi
}

sendjob()
{
    for FILE in *.mp4; do
        [ -f "$FILE" ] || continue
        echo "ffmpeg -y -i $WORKDIR/src/$srcstring/$FILE -hide_banner $ENCODER_FLAGS -f mp4 $WORKDIR/out/$srcstring/$FILE > $LOGDIR/ffmpeg.log 2>&1" > $WORKDIR/ffmpeg-queue
        sleep 1s;
        notify
        mv $FILE $WORKDIR/raw-src/$srcstring/
    done
}

sendjob 2> /dev/null;
cd $WORKDIR
