#!/bin/bash
source config

cd $WORKDIR/src;
shopt -s nullglob

sendjob()
{
    for FILE in *.mp4; do
        [ -f "$FILE" ] || continue
        echo "ffmpeg -y -i $WORKDIR/src/$FILE -hide_banner $ENCODER_FLAGS $WORKDIR/out/$FILE > $LOGDIR/ffmpeg.log 2>&1" > $WORKDIR/ffmpeg-queue
        sleep 1s;
        mv $FILE $WORKDIR/raw-src
    done
}

sendjob 2> /dev/null;
cd $WORKDIR
