#!/bin/bash
source config



cd $LOGDIR;
find . -type f \( -name "*.log" -not -name "ffmpeg.log" -not -name "ffmpeg.log.old" \) -print0 | xargs -I{} -0 rm {};

for file in ffmpeg.log.old; do
    tail -200000 "$file" > "$file.tmp" # retain 200k lines of logs in ffmpeg.old
    mv -- "$file.tmp" "$file"
done

echo "nuked" > ffmpeg.log;
printf "\n\n${BLUE}logs nuked!${NC}\n"
ls -lah $LOGDIR
