#!/bin/bash
WORKDIR=/chronos/Archivar

# Coloring
BLUE='\033[0;34m'
NC='\033[0m'

cd $WORKDIR/log;
find . -type f \( -name "*.log" -not -name "ffmpeg.log" -not -name "ffmpeg.log.old" \) -print0 | xargs -I{} -0 rm {};/

for file in ffmpeg.log.old; do
    tail -200000 "$file" > "$file.tmp" # retain 200k lines of logs in ffmpeg.old
    mv -- "$file.tmp" "$file"
done

echo "nuked" > ffmpeg.log;
printf "\n\n${BLUE}logs nuked!${NC}\n"
ls -lah /chronos/Archivar/log
